Add new feature flag
This is necessary to prevent a type error in the `useFeatureFlags` hook, which depends on there being at least one FF. Otherwise, we will get the error TS2322: Type any is not assignable to type never.

I could have worked around this, but I thought it unnecessary since we will undoubtedly add more flags in the future